<a href="https://colab.research.google.com/github/larissavaladao/time_series_curuai/blob/main/5.%20parameters_by_period/5.discharge_timeseries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# import and install packages

In [1]:
import pandas as pd
import seaborn as sns

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# import data

In [3]:
#vou precisar mudar a lógica para agregar, pegando os dias em vez das medias mensais no caso das cotas

# import discharge database
df = pd.read_csv('/content/drive/MyDrive/CURUAI_PROCESS/17050001_Vazoes.csv')#.dropna(subset=['Maxima','Media', 'Minima'])
# df = pd.read_csv('C:/Users/l_v_v/Documents/GitHub/py6s_harmonize_sample/datasets/HydroWeb/17050001_Vazoes.csv')
df['Data'] = pd.to_datetime(df['Data'],dayfirst=True)

df = df[['Data', 'Vazao01', 'Vazao02', 'Vazao03',
       'Vazao04', 'Vazao05', 'Vazao06', 'Vazao07', 'Vazao08', 'Vazao09',
       'Vazao10', 'Vazao11', 'Vazao12', 'Vazao13', 'Vazao14', 'Vazao15',
       'Vazao16', 'Vazao17', 'Vazao18', 'Vazao19', 'Vazao20', 'Vazao21',
       'Vazao22', 'Vazao23', 'Vazao24', 'Vazao25', 'Vazao26', 'Vazao27',
       'Vazao28', 'Vazao29', 'Vazao30', 'Vazao31','Maxima','Media', 'Minima']].copy()
df

,Data,Vazao01,Vazao02,Vazao03,Vazao04,Vazao05,Vazao06,Vazao07,Vazao08,Vazao09,...,Vazao25,Vazao26,Vazao27,Vazao28,Vazao29,Vazao30,Vazao31,Maxima,Media,Minima
0,2024-12-01,70882.820,71476.32,72471.990,73677.580,73906.730,73906.730,73677.580,75022.44,75823.200,...,90945.390,92496.49,93536.016,94928.810,96504.920,98267.540,99864.100,99864.100,83155.860,70882.820
1,2024-11-01,54925.973,55607.24,55436.457,56293.480,55949.740,54418.280,53078.055,51757.56,51921.547,...,65484.040,66239.82,67000.750,67766.820,68731.670,69509.370,NaN,69509.370,60805.510,51757.560
2,2024-10-01,61237.440,60695.93,59443.450,60516.055,60876.117,59799.723,57680.938,55949.74,54756.430,...,54081.367,53244.50,52911.914,53078.055,52911.914,52415.348,53745.695,61237.440,54955.098,50618.246
3,2024-09-01,121290.836,119002.37,116919.000,115224.710,112793.820,110567.210,108357.290,105982.15,103446.440,...,70292.250,67383.14,65108.066,63432.030,61963.895,61781.805,NaN,121290.836,89971.480,61781.805
4,2024-08-01,173959.730,172562.48,171168.980,169779.250,168854.860,167932.160,166551.270,165403.44,163800.900,...,138566.360,136760.12,134365.690,131592.250,129232.336,126499.380,124174.336,173959.730,152110.640,124174.336
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
676,1968-05-01,186702.720,187419.42,187897.730,190055.170,191257.300,191738.840,192220.810,193427.47,193910.830,...,201699.140,202925.28,203170.800,203907.970,203662.140,203416.420,203907.970,203907.970,197769.300,186702.720
677,1968-04-01,164029.530,164487.08,164487.080,164716.000,165632.780,166091.810,166551.270,166551.27,167011.140,...,181711.470,182184.88,182895.770,183607.580,184082.620,185510.230,NaN,185510.230,173898.780,164029.530
678,1968-03-01,147523.980,147318.08,147523.980,147936.140,147936.140,147730.000,147318.080,147936.14,148761.730,...,160838.640,161520.64,161975.840,162659.450,163344.000,163572.400,164029.530,164029.530,154791.720,147318.080
679,1968-02-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,140786.020,143018.88,143426.270,144446.620,146084.860,NaN,NaN,NaN,NaN,NaN
680,1968-01-01,103000.000,105000.00,106000.000,106000.000,106000.000,107000.000,107000.000,107000.00,107000.000,...,115000.000,116000.00,117000.000,117000.000,118000.000,119000.000,120000.000,120000.000,110677.420,103000.000

#adicionar periodos por mes

In [ ]:
def add_period(row):
    if row['Data'][3:5] == '01' or row['Data'][3:5] == '02' or row['Data'][3:5] == '03':
        val = 'R'
    elif row['Data'][3:5] == '04' or row['Data'][3:5] == '05' or row['Data'][3:5] == '06':
        val = 'HW'
    elif row['Data'][3:5] == '07' or row['Data'][3:5] == '08' or row['Data'][3:5] == '09':
        val = 'F'
    else:
        val = 'LW'
    return val

def add_start_period(row):
    if row['Data'][3:5] == '01' or row['Data'][3:5] == '02' or row['Data'][3:5] == '03':
        val = 1
    elif row['Data'][3:5] == '04' or row['Data'][3:5] == '05' or row['Data'][3:5] == '06':
        val = 4
    elif row['Data'][3:5] == '07' or row['Data'][3:5] == '08' or row['Data'][3:5] == '09':
        val = 7
    else:
        val = 10
    return val

def add_start_year(row):
    return int(row['Data'][6:10])

In [ ]:
df['water_period'] = df.apply(add_period, axis=1)
df['start_month'] = df.apply(add_start_period, axis=1)
df['year'] = df.apply(add_start_year, axis=1)
df

,EstacaoCodigo,NivelConsistencia,Data,Hora,MediaDiaria,MetodoObtencaoVazoes,Maxima,Minima,Media,DiaMaxima,...,Vazao25Status,Vazao26Status,Vazao27Status,Vazao28Status,Vazao29Status,Vazao30Status,Vazao31Status,water_period,start_month,year
0,17050001,1,01/10/2024,NaN,1,1,61237.44,50618.246,54955.098,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LW,10,2024
1,17050001,1,01/04/2024,NaN,1,1,199498.36,171633.060,185468.000,30.0,...,1.0,1.0,1.0,1.0,1.0,1.0,0.0,HW,4,2024
2,17050001,1,01/03/2024,NaN,1,1,171400.97,150210.660,161591.580,31.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,R,1,2024
3,17050001,1,01/02/2024,NaN,1,1,149589.05,131000.770,140958.220,29.0,...,1.0,1.0,1.0,1.0,1.0,0.0,0.0,R,1,2024
4,17050001,1,01/01/2024,NaN,1,1,130607.01,101291.350,117846.250,31.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,R,1,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
669,17050001,2,01/05/1968,NaN,1,1,203907.97,186702.720,197769.300,28.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,HW,4,1968
670,17050001,2,01/04/1968,NaN,1,1,185510.23,164029.530,173898.780,30.0,...,1.0,1.0,1.0,1.0,1.0,1.0,NaN,HW,4,1968
671,17050001,2,01/03/1968,NaN,1,1,164029.53,147318.080,154791.720,31.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,R,1,1968
672,17050001,2,01/02/1968,NaN,1,1,NaN,NaN,NaN,NaN,...,1.0,1.0,1.0,1.0,1.0,NaN,NaN,R,1,1968
673,17050001,2,01/01/1968,NaN,1,1,120000.00,103000.000,110677.420,31.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,R,1,1968

## Agregar por mes

In [ ]:
df_discharge = df[['EstacaoCodigo','Data',  'Maxima', 'Minima', 'Media','water_period',
'start_month','year']].copy()
df_discharge.describe()

,Data,day,month,year,longitude,latitude,media_vazao
count,100,100.000000,100.000000,100.000000,1.000000e+02,1.000000e+02,100.000000
mean,2012-05-07 18:51:51.887551744,15.670000,6.380000,2011.860000,-5.551310e+01,-1.919200e+00,162010.813447
min,2000-01-13 10:43:38.181818240,1.000000,1.000000,2000.000000,-5.551310e+01,-1.919200e+00,100246.712936
25%,2006-01-23 09:53:06.061016960,7.000000,2.000000,2005.750000,-5.551310e+01,-1.919200e+00,138800.780412
50%,2012-05-04 11:31:12,16.500000,8.000000,2012.000000,-5.551310e+01,-1.919200e+00,163826.842264
75%,2018-08-23 02:21:44.215700992,24.000000,9.000000,2018.000000,-5.551310e+01,-1.919200e+00,184859.775743
max,2024-05-30 21:51:25.714285824,31.000000,12.000000,2024.000000,-5.551310e+01,-1.919200e+00,228570.401542
std,NaN,9.407771,3.818562,7.244671,5.712979e-14,1.785306e-15,30431.903447

In [ ]:
df_discharge['Data']=pd.to_datetime(df_discharge['Data'],format="%d/%m/%Y")

In [ ]:
df_media_vazao.dtypes

Data            datetime64[ns]
type                    object
day                      int32
month                    int32
year                     int32
longitude              float64
latitude               float64
time_start              object
water_period            object
media_vazao            float64
dtype: object

In [ ]:
df_media_vazao.head()

,Data,type,day,month,year,longitude,latitude,time_start,water_period,media_vazao
0,2000-01-13 10:43:38.181818240,LW_to_R,13,1,2000,-55.5131,-1.9192,2000-01-13,R,149214.789000
1,2000-02-29 18:17:42.295081984,R_to_HW,29,2,2000,-55.5131,-1.9192,2000-02-29,HW,183025.310285
2,2000-08-24 20:45:42.857142784,HW_to_F,24,8,2000,-55.5131,-1.9192,2000-08-24,F,169613.685000
3,2000-09-28 10:23:44.598930432,F_to_LW,28,9,2000,-55.5131,-1.9192,2000-09-28,LW,136244.920211
4,2001-01-05 16:27:54.418604672,LW_to_R,5,1,2001,-55.5131,-1.9192,2001-01-05,R,149854.912953

In [ ]:
df_discharge = df_discharge.loc[(df_discharge['Data'] > pd.to_datetime('2000-01-01')) & (df_discharge['Data'] < pd.to_datetime('2025-01-01'))]
df_discharge

,EstacaoCodigo,Data,Maxima,Minima,Media,water_period,start_month,year
0,17050001,2024-10-01,61237.44,50618.246,54955.098,LW,10,2024
1,17050001,2024-04-01,199498.36,171633.060,185468.000,HW,4,2024
2,17050001,2024-03-01,171400.97,150210.660,161591.580,R,1,2024
3,17050001,2024-02-01,149589.05,131000.770,140958.220,R,1,2024
4,17050001,2024-01-01,130607.01,101291.350,117846.250,R,1,2024
...,...,...,...,...,...,...,...,...
284,17050001,2000-06-01,231542.98,223636.860,227736.890,HW,4,2000
285,17050001,2000-05-01,230773.88,220601.100,227064.900,HW,4,2000
286,17050001,2000-04-01,219844.31,196090.950,208611.500,HW,4,2000
287,17050001,2000-03-01,195848.31,165403.440,181084.640,R,1,2000
288,17050001,2000-02-01,166091.81,140179.340,153418.560,R,1,2000

In [ ]:
aggregated_data = df_discharge.groupby(['water_period', 'year','start_month']).agg(
    Maxima=('Maxima', 'mean'),
    Minima=('Minima', 'mean'),
    Media=('Media', 'mean')
).sort_values(by=['year','start_month'])

In [ ]:
aggregated_data

                                      Maxima         Minima          Media
water_period year start_month
R            2000 1            180970.060000  152791.390000  167251.600000
HW           2000 4            227387.056667  213442.970000  221137.763333
F            2000 7            210227.493333  187716.696667  199513.620000
LW           2000 10           131677.151667  112206.038667  119414.215000
R            2001 1            180008.923333  151748.301667  165210.756667
...                                      ...            ...            ...
F            2023 7            193004.146667  150315.096667  174020.018667
LW           2023 10            86783.280000   63105.949667   71733.411333
R            2024 1            150532.343333  127500.926667  140132.016667
HW           2024 4            199498.360000  171633.060000  185468.000000
LW           2024 10            61237.440000   50618.246000   54955.098000

[98 rows x 3 columns]

In [ ]:
aggregated_data.to_csv('C:/Users/l_v_v/Documents/GitHub/py6s_harmonize_sample/datasets/Parameters Time series/mean_watershed_discharge.csv')

In [ ]:
view = pd.read_csv('C:/Users/l_v_v/Documents/GitHub/py6s_harmonize_sample/datasets/Parameters Time series/mean_watershed_discharge.csv')
view

,water_period,year,start_month,Maxima,Minima,Media
0,R,2000,1,180970.060000,152791.390000,167251.600000
1,HW,2000,4,227387.056667,213442.970000,221137.763333
2,F,2000,7,210227.493333,187716.696667,199513.620000
3,LW,2000,10,131677.151667,112206.038667,119414.215000
4,R,2001,1,180008.923333,151748.301667,165210.756667
...,...,...,...,...,...,...
93,F,2023,7,193004.146667,150315.096667,174020.018667
94,LW,2023,10,86783.280000,63105.949667,71733.411333
95,R,2024,1,150532.343333,127500.926667,140132.016667
96,HW,2024,4,199498.360000,171633.060000,185468.000000
97,LW,2024,10,61237.440000,50618.246000,54955.098000

# adicionar periodos por cota obidos

In [4]:
df['month'] = df['Data'].dt.month
df['year'] = df['Data'].dt.year
df['day'] = df['Data'].dt.day
df

,Data,Vazao01,Vazao02,Vazao03,Vazao04,Vazao05,Vazao06,Vazao07,Vazao08,Vazao09,...,Vazao28,Vazao29,Vazao30,Vazao31,Maxima,Media,Minima,month,year,day
0,2024-12-01,70882.820,71476.32,72471.990,73677.580,73906.730,73906.730,73677.580,75022.44,75823.200,...,94928.810,96504.920,98267.540,99864.100,99864.100,83155.860,70882.820,12,2024,1
1,2024-11-01,54925.973,55607.24,55436.457,56293.480,55949.740,54418.280,53078.055,51757.56,51921.547,...,67766.820,68731.670,69509.370,NaN,69509.370,60805.510,51757.560,11,2024,1
2,2024-10-01,61237.440,60695.93,59443.450,60516.055,60876.117,59799.723,57680.938,55949.74,54756.430,...,53078.055,52911.914,52415.348,53745.695,61237.440,54955.098,50618.246,10,2024,1
3,2024-09-01,121290.836,119002.37,116919.000,115224.710,112793.820,110567.210,108357.290,105982.15,103446.440,...,63432.030,61963.895,61781.805,NaN,121290.836,89971.480,61781.805,9,2024,1
4,2024-08-01,173959.730,172562.48,171168.980,169779.250,168854.860,167932.160,166551.270,165403.44,163800.900,...,131592.250,129232.336,126499.380,124174.336,173959.730,152110.640,124174.336,8,2024,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
676,1968-05-01,186702.720,187419.42,187897.730,190055.170,191257.300,191738.840,192220.810,193427.47,193910.830,...,203907.970,203662.140,203416.420,203907.970,203907.970,197769.300,186702.720,5,1968,1
677,1968-04-01,164029.530,164487.08,164487.080,164716.000,165632.780,166091.810,166551.270,166551.27,167011.140,...,183607.580,184082.620,185510.230,NaN,185510.230,173898.780,164029.530,4,1968,1
678,1968-03-01,147523.980,147318.08,147523.980,147936.140,147936.140,147730.000,147318.080,147936.14,148761.730,...,162659.450,163344.000,163572.400,164029.530,164029.530,154791.720,147318.080,3,1968,1
679,1968-02-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,144446.620,146084.860,NaN,NaN,NaN,NaN,NaN,2,1968,1
680,1968-01-01,103000.000,105000.00,106000.000,106000.000,106000.000,107000.000,107000.000,107000.00,107000.000,...,117000.000,118000.000,119000.000,120000.000,120000.000,110677.420,103000.000,1,1968,1

In [5]:
#import period dates
df_period_limits = pd.read_csv('/content/drive/MyDrive/CURUAI_PROCESS/water_period_limits.csv').drop(columns=['Unnamed: 0'])
df_period_limits['time_start'] = df_period_limits['Data'].apply(lambda x : x[0:10])
df_period_limits['Data'] = pd.to_datetime(df_period_limits['Data'])
#
# df_period_limits['date'] = pd.to_datetime(df_period_limits['date'])
df_period_limits['month'] = df_period_limits['Data'].dt.month
df_period_limits['year'] = df_period_limits['Data'].dt.year
df_period_limits['day'] = df_period_limits['Data'].dt.day

df_period_limits

,Data,type,day,month,year,longitude,latitude,time_start
0,1990-01-18 01:12:00.000000000,LW_to_R,18,1,1990,-55.5131,-1.9192,1990-01-18
1,1990-02-23 01:06:12.413793152,R_to_HW,23,2,1990,-55.5131,-1.9192,1990-02-23
2,1990-08-06 23:15:16.770186368,HW_to_F,6,8,1990,-55.5131,-1.9192,1990-08-06
3,1990-09-09 06:25:30.708661376,F_to_LW,9,9,1990,-55.5131,-1.9192,1990-09-09
4,1990-12-22 21:55:51.724137856,LW_to_R,22,12,1990,-55.5131,-1.9192,1990-12-22
...,...,...,...,...,...,...,...,...
125,2023-08-01 20:06:29.189189120,HW_to_F,1,8,2023,-55.5131,-1.9192,2023-08-01
126,2023-08-25 18:37:31.737451520,LW_to_R,25,8,2023,-55.5131,-1.9192,2023-08-25
127,2024-03-25 23:32:02.330097152,R_to_HW,25,3,2024,-55.5131,-1.9192,2024-03-25
128,2024-04-06 10:42:51.428571648,HW_to_F,6,4,2024,-55.5131,-1.9192,2024-04-06
129,2024-05-30 21:51:25.714285824,F_to_L,30,5,2024,-55.5131,-1.9192,2024-05-30

In [6]:
import numpy as np
import math
# print()
# df
# df_period_limits

#avaliar se dá ruim quando o periodo se inicia em um ano e termina em outro

# def set_period(row):
#   return df_period_limits.loc[(df_period_limits['month'] == row['month'])&(df_period_limits['year'] == row['year'])]['type'].values[0]
lista_periodo = []
lista_media_vazao = []
for i in range(0,len(df_period_limits)-1):
# for i in range(0,5):
  if df_period_limits['year'][i+1] == df_period_limits['year'][i]:
    x = df.loc[df['year'] >= df_period_limits['year'][i] ].copy()
    x = x.loc[x['year'] <= df_period_limits['year'][i+1]].copy()
    x = x.loc[x['month'] >= df_period_limits['month'][i] ].copy()
    x = x.loc[x['month'] <= df_period_limits['month'][i+1]].copy()
    x = x.drop(columns=['Data','year','month','day','Maxima','Media','Minima'])
    print( len(x))
    print(x)
    print(str('Vazao')+str(df_period_limits['day'][i]))
    print(str('Vazao')+str(df_period_limits['day'][i+1]))

  else:
    x = df.loc[df['year'] == df_period_limits['year'][i] ].copy()
    x = x.loc[x['month'] >= df_period_limits['month'][i] ].copy()



    y = df.loc[df['year'] == df_period_limits['year'][i+1]].copy()
    y = y.loc[y['month'] <= df_period_limits['month'][i+1]].copy()


    x = pd.concat([x,y]).drop(columns=['Data','year','month','day','Maxima','Media','Minima'])
    print( len(x))
    print(x)
    print(str('Vazao')+str(df_period_limits['day'][i]))
    print(str('Vazao')+str(df_period_limits['day'][i+1]))




  lista_periodo.append(df_period_limits['type'][i])

  lista_dias = []
  x_1 = x[0:1].copy()
  # print(x_1)
  for j in range(int(df_period_limits['day'][i]),31):
    # print(j)
    if j < 10:
      media1 = x_1[str('Vazao0')+str(j)].mean()
      lista_dias.append(media1)

    else:
      media1 = x_1[str('Vazao')+str(j)].mean()
      lista_dias.append(media1)
  # print(lista_dias)
  x_2 = x[-1:].copy()
    # print(x_2)
  for k in range(int(df_period_limits['day'][i+1]),31):
        # print(k)
    if k < 10:
      media2 = x_2[str('Vazao0')+str(k)]
      lista_dias.append(media2.mean())
      # print(media2)
    else:
      media2 = x_2[str('Vazao')+str(k)]
      lista_dias.append(media2.mean())
      # print(media2)
  cleaned = [x for x in lista_dias if not (isinstance(x, float) and math.isnan(x))]
  cleaned_mean = sum(cleaned)/len(lista_dias)


  if len(x) > 2:
    media = x[1:-1].mean(axis=1).mean()
    cleaned_mean = (media + cleaned_mean)/2

  lista_media_vazao.append(cleaned_mean)


    # print(lista_media_vazao)
  print(lista_periodo)
  print()
    #

    # periodo = str(df_period_limits['type'][i])
    # print(periodo)

2
       Vazao01    Vazao02    Vazao03     Vazao04    Vazao05    Vazao06  \
415  131592.25  132580.27  133571.06  134166.860  135162.06  136559.98
416  124367.48  123981.31  123402.92  122633.305  121482.27  120908.29

        Vazao07     Vazao08     Vazao09    Vazao10  ...    Vazao22    Vazao23  \
415  137762.500  139371.970  140583.690  142611.92  ...  160611.52  161748.19
416  120526.195  120144.555  119763.375  119953.91  ...  118622.55  118812.40

        Vazao24    Vazao25    Vazao26    Vazao27    Vazao28    Vazao29  \
415  163800.900  165862.25  167932.16  170705.31  172562.48        NaN
416  119763.375  120908.29  122057.28  123402.92  125141.14  126693.87

       Vazao30     Vazao31
415        NaN         NaN
416  128449.26  130017.195

[2 rows x 31 columns]
Vazao18
Vazao23
['LW_to_R']

7
       Vazao01    Vazao02    Vazao03    Vazao04    Vazao05    Vazao06  \
409  199498.36  198279.19  197548.88  197062.50  196576.53  195848.31
410  212823.02  212324.40  211826.19  211328.36  210582.34  209589.03
411  216825.89  217327.98  216574.98  216574.98  216324.17  215822.83
412  212075.23  212324.40  212324.40  213072.45  213571.66  213571.66
413  200231.06  200720.03  200475.50  200475.50  200720.03  200964.66
414  173726.61  175594.62  177000.00  178174.00  179350.58  181474.92
415  131592.25  132580.27  133571.06  134166.86  135162.06  136559.98

       Vazao07    Vazao08    Vazao09    Vazao10  ...    Vazao22    Vazao23  \
409  195121.00  194636.64  194394.60  194152.67  ...  183607.58  183132.94
410  209092.95  208845.08  208597.28  208597.28  ...  203416.42  203416.42
411  215321.89  214821.34  215071.56  215071.56  ...  213821.39  213571.66
412  213821.39  213821.39  214071.23  214821.34  ...  215321.89  215572.31
413  201454.22  201944.17  203170.80  203662.14  ...  206865.50  207112.61
414  183132.94  184082.62  185033.97  186225.42  ...  193910.83  193910.83
415  137762.50  139371.97  140583.69  142611.92  ...  160611.52  161748.19

       Vazao24    Vazao25    Vazao26    Vazao27    Vazao28    Vazao29  \
409  182184.88  181002.12  179586.20  178409.11  177469.28  175828.60
410  203416.42  202925.28  202434.53  202434.53  202434.53  201699.14
411  213322.00  213821.39  213571.66  213322.00  213322.00  212823.02
412  215822.83  216324.17  216324.17  216825.89  216825.89  216324.17
413  207359.81  208102.00  209092.95  209837.20  210582.34  211079.58
414  194636.64  195363.34  196333.69  197062.50  198279.19  199010.39
415  163800.90  165862.25  167932.16  170705.31  172562.48        NaN

       Vazao30    Vazao31
409  174192.98  172795.10
410  200475.50  200231.06
411  212823.02        NaN
412  216324.17  216825.89
413  211577.22        NaN
414  199254.33  200231.06
415        NaN        NaN

[7 rows x 31 columns]
Vazao23
Vazao6
['LW_to_R', 'R_to_HW']

2
       Vazao01    Vazao02    Vazao03    Vazao04    Vazao05    Vazao06  \
408  171633.06  170705.31  169316.84  167701.75  167011.14  166091.81
409  199498.36  198279.19  197548.88  197062.50  196576.53  195848.31

       Vazao07    Vazao08    Vazao09    Vazao10  ...    Vazao22    Vazao23  \
408  164945.03  164029.53  162887.53  161293.20  ...  142408.61  141596.44
409  195121.00  194636.64  194394.60  194152.67  ...  183607.58  183132.94

       Vazao24    Vazao25    Vazao26    Vazao27     Vazao28     Vazao29  \
408  139775.44  138767.60  135560.92  132778.20  130017.195  128253.766
409  182184.88  181002.12  179586.20  178409.11  177469.280  175828.600

       Vazao30   Vazao31
408  126693.87       NaN
409  174192.98  172795.1

[2 rows x 31 columns]
Vazao6
Vazao9
['LW_to_R', 'R_to_HW', 'HW_to_F']

4
        Vazao01     Vazao02    Vazao03    Vazao04    Vazao05     Vazao06  \
405   95803.230   96856.484   98621.49  100576.77  101470.29  102366.766
406   82674.555   83504.930   84672.67   86014.67   86857.43   87533.860
407  125334.836  123788.410  122441.19  122057.28  120717.19  119382.640
408  171633.060  170705.310  169316.84  167701.75  167011.14  166091.810

       Vazao07    Vazao08    Vazao09    Vazao10  ...     Vazao22    Vazao23  \
405  104349.41  105800.26  106164.15  105982.15  ...  120335.320  121099.50
406   88552.18   87703.27   87195.40   87195.40  ...   92669.445   93015.71
407  118812.40  117107.83  116730.29  114287.45  ...   92669.445   91117.25
408  164945.03  164029.53  162887.53  161293.20  ...  142408.610  141596.44

        Vazao24     Vazao25    Vazao26     Vazao27     Vazao28     Vazao29  \
405  122633.305  123017.890  123788.41  124947.555  125722.570  126693.870
406   91805.900   91633.555   91978.37   91978.370   92669.445   92842.516
407   89233.510   87703.270   85846.49   84171.470   82840.380   82012.500
408  139775.440  138767.600  135560.92  132778.200  130017.195  128253.766

       Vazao30     Vazao31
405  127667.97  129428.380
406   94231.45         NaN
407   80694.38   81352.445
408  126693.87         NaN

[4 rows x 31 columns]
Vazao9
Vazao22
['LW_to_R', 'R_to_HW', 'HW_to_F', 'F_to_LW']

4
       Vazao01     Vazao02    Vazao03    Vazao04    Vazao05     Vazao06  \
405   95803.23   96856.484   98621.49  100576.77  101470.29  102366.766
402  177469.28  177469.280  177469.28  177469.28  177234.60  176531.120
403  170010.61  172097.560  173493.56  173726.61  173959.73  174192.980
404  131000.77  131789.640  133174.40  133968.16  134962.81  135560.920

       Vazao07    Vazao08    Vazao09    Vazao10  ...    Vazao22    Vazao23  \
405  104349.41  105800.26  106164.15  105982.15  ...  120335.32  121099.50
402  176531.12  176531.12  175594.62  175594.62  ...  182895.77  183607.58
403  174426.33  174192.98  174192.98  173959.73  ...  177469.28  177234.60
404  136559.98  137160.75  137561.80  138164.20  ...  154798.62  155866.81

        Vazao24    Vazao25    Vazao26     Vazao27    Vazao28    Vazao29  \
405  122633.305  123017.89  123788.41  124947.555  125722.57  126693.87
402  183845.060  183607.58  183845.06  184795.980  185986.92  187180.42
403  177000.000  176062.67  176296.84  176296.840  177000.00        NaN
404  157443.110  159024.69  160384.52  161975.840  163344.00  165174.19

       Vazao30    Vazao31
405  127667.97  129428.38
402  188137.05  189575.03
403        NaN        NaN
404  167471.44  168854.86

[4 rows x 31 columns]
Vazao22
Vazao1
['LW_to_R', 'R_to_HW', 'HW_to_F', 'F_to_LW', 'LW_to_R']

6
       Vazao01    Vazao02    Vazao03    Vazao04    Vazao05    Vazao06  \
397  201944.17  201944.17  201944.17  201699.14  200964.66  200231.06
398  216574.98  216324.17  215572.31  214821.34  214321.17  213821.39
399  220348.73  220601.10  221106.10  220853.55  220601.10  220601.10
400  210333.86  211079.58  211577.22  212075.23  212573.66  213072.45
401  190776.14  191257.30  192220.81  193185.94  193910.83  194636.64
402  177469.28  177469.28  177469.28  177469.28  177234.60  176531.12

       Vazao07    Vazao08    Vazao09    Vazao10  ...    Vazao22    Vazao23  \
397  199498.36  199254.33  199010.39  199010.39  ...  187897.73  186702.72
398  213821.39  213821.39  213072.45  212573.66  ...  207607.11  206618.50
399  220096.48  219844.31  220348.73  220348.73  ...  220348.73  220348.73
400  213571.66  213322.00  213821.39  214071.23  ...  219844.31  219844.31
401  194394.60  195848.31  196333.69  196819.47  ...  207112.61  207112.61
402  176531.12  176531.12  175594.62  175594.62  ...  182895.77  183607.58

       Vazao24    Vazao25    Vazao26    Vazao27    Vazao28    Vazao29  \
397  185272.05  184795.98  184558.10  183607.58  181948.12  181238.47
398  205138.55  204399.90  204153.89  203416.42  203170.80  202925.28
399  219844.31  219592.25  218081.88  217830.48  217579.19  217327.98
400  219844.31  220348.73  220096.48  220096.48  220348.73  220601.10
401  207359.81  207854.50  208102.00  208845.08  209092.95  209589.03
402  183845.06  183607.58  183845.06  184795.98  185986.92  187180.42

       Vazao30    Vazao31
397  180529.73  179821.94
398  202679.86  202434.53
399  217579.19        NaN
400  220601.10  220601.10
401  209837.20        NaN
402  188137.05  189575.03

[6 rows x 31 columns]
Vazao1
Vazao10
['LW_to_R', 'R_to_HW', 'HW_to_F', 'F_to_LW', 'LW_to_R', 'R_to_HW']

2
       Vazao01    Vazao02    Vazao03    Vazao04    Vazao05    Vazao06  \
396  179115.06  177704.10  175828.60  174192.98  172795.10  171400.97
397  201944.17  201944.17  201944.17  201699.14  200964.66  200231.06

       Vazao07    Vazao08    Vazao09    Vazao10  ...    Vazao22    Vazao23  \
396  170010.61  169085.80  167932.16  166781.16  ...  142408.61  140583.69
397  199498.36  199254.33  199010.39  199010.39  ...  187897.73  186702.72

       Vazao24    Vazao25    Vazao26    Vazao27    Vazao28    Vazao29  \
396  138566.36  136760.12  135760.52  134166.86  131987.12  129820.81
397  185272.05  184795.98  184558.10  183607.58  181948.12  181238.47

       Vazao30    Vazao31
396  128058.39        NaN
397  180529.73  179821.94

[2 rows x 31 columns]
Vazao10
Vazao10
['LW_to_R', 'R_to_HW', 'HW_to_F', 'F_to_LW', 'LW_to_R', 'R_to_HW', 'HW_to_F']

6
        Vazao01    Vazao02     Vazao03     Vazao04     Vazao05     Vazao06  \
393   89574.914   90087.93   90259.180   90945.390   91633.555   92496.490
394   85175.000   83338.61   82674.555   82674.555   82508.860   82674.555
395  125916.610  123595.60  121673.830  119572.950  117485.820  115976.586
396  179115.060  177704.10  175828.600  174192.980  172795.100  171400.970
391  120335.320  121099.50  121673.830  122825.540  123595.600  124560.720
392  102726.190  102726.19  102906.070  102906.070  103807.270  103987.870

        Vazao07    Vazao08     Vazao09     Vazao10  ...     Vazao22  \
393   93362.460   93883.49   93883.490   94057.414  ...   98267.540
394   83338.610   83671.38   83671.380   83172.410  ...   85007.430
395  114662.010  113353.07  112049.766  111122.300  ...   93362.460
396  170010.610  169085.80  167932.160  166781.160  ...  142408.610
391  124947.555  125141.14  125334.836  124947.555  ...  126305.016
392  104349.410  104892.59  104892.590  104530.350  ...  112235.600

        Vazao23     Vazao24     Vazao25     Vazao26     Vazao27     Vazao28  \
393   99508.480  100576.770  102007.820  102366.766  102366.766  102187.234
394   86182.980   87026.350   88552.180   89062.990   89233.510   88892.600
395   93189.020   92842.516   92842.516   92842.516   91633.555   89745.800
396  140583.690  138566.360  136760.120  135760.520  134166.860  131987.120
391  126305.016  125916.610  125528.650  125141.140  125141.140  125141.140
392  114100.340  115412.510  116164.836  116353.210  116919.000  118243.190

        Vazao29     Vazao30     Vazao31
393  102187.234  102366.766  102546.414
394   88722.330   89062.990         NaN
395   89062.990   87195.400   86182.980
396  129820.810  128058.390         NaN
391  125334.836         NaN         NaN
392  118432.810  119002.370  119572.950

[6 rows x 31 columns]
Vazao10
Vazao19
['LW_to_R', 'R_to_HW', 'HW_to_F', 'F_to_LW', 'LW_to_R', 'R_to_HW', 'HW_to_F', 'F_to_LW']

3
       Vazao01    Vazao02    Vazao03    Vazao04    Vazao05    Vazao06  \
389  168162.67  169548.00  170937.10  172097.56  173027.81  174192.98
390  125722.57  126693.87  127667.97  128449.26  129624.54  130213.69
391  120335.32  121099.50  121673.83  122825.54  123595.60  124560.72

        Vazao07    Vazao08     Vazao09     Vazao10  ...     Vazao22  \
389  175594.620  176531.12  177234.600  177469.280  ...  185986.920
390  131592.250  132778.20  133769.550  135361.440  ...  153960.600
391  124947.555  125141.14  125334.836  124947.555  ...  126305.016

        Vazao23    Vazao24    Vazao25    Vazao26    Vazao27    Vazao28  \
389  186464.020  186702.72  186702.72  186702.72  186702.72  186702.72
390  155192.880  157443.11  158798.42  159704.11  160838.64  162203.61
391  126305.016  125916.61  125528.65  125141.14  125141.14  125141.14

        Vazao29    Vazao30    Vazao31
389  186941.520  187419.42        NaN
390  164029.530  164945.03  166091.81
391  125334.836        NaN        NaN

[3 rows x 31 columns]
Vazao19
Vazao1
['LW_to_R', 'R_to_HW', 'HW_to_F', 'F_to_LW', 'LW_to_R', 'R_to_HW', 'HW_to_F', 'F_to_LW', 'LW_to_R']

2
       Vazao01    Vazao02    Vazao03    Vazao04    Vazao05    Vazao06  \
388  187180.42  187658.53  188137.05  188615.97  189095.30  189335.12
389  168162.67  169548.00  170937.10  172097.56  173027.81  174192.98

       Vazao07    Vazao08    Vazao09    Vazao10  ...    Vazao22    Vazao23  \
388  189335.12  190055.17  190055.17  190055.17  ...  188615.97  187658.53
389  175594.62  176531.12  177234.60  177469.28  ...  185986.92  186464.02

       Vazao24    Vazao25    Vazao26    Vazao27    Vazao28    Vazao29  \
388  187419.42  186702.72  186225.42  185272.05  184795.98  184795.98
389  186702.72  186702.72  186702.72  186702.72  186702.72  186941.52

       Vazao30    Vazao31
388  184082.62  183607.58
389  187419.42        NaN

[2 rows x 31 columns]
Vazao1
Vazao22
['LW_to_R', 'R_to_HW', 'HW_to_F', 'F_to_LW', 'LW_to_R', 'R_to_HW', 'HW_to_F', 'F_to_LW', 'LW_to_R', 'R_to_HW']

3
       Vazao01    Vazao02    Vazao03    Vazao04    Vazao05    Vazao06  \
386  166781.16  166321.48  166091.81  165862.25  165403.44  164716.00
387  183132.94  183132.94  183132.94  183132.94  182658.70  182658.70
388  187180.42  187658.53  188137.05  188615.97  189095.30  189335.12

       Vazao07    Vazao08    Vazao09    Vazao10  ...    Vazao22    Vazao23  \
386  163572.40  163115.72  162431.47  161293.20  ...  153124.28  152289.67
387  182184.88  181948.12  181238.47  181238.47  ...  174192.98  173726.61
388  189335.12  190055.17  190055.17  190055.17  ...  188615.97  187658.53

       Vazao24    Vazao25    Vazao26    Vazao27    Vazao28    Vazao29  \
386  150625.61  149589.05  149175.17  148968.39  148348.72  147936.14
387  172795.10  171865.25  171168.98  169779.25  169316.84  168624.03
388  187419.42  186702.72  186225.42  185272.05  184795.98  184795.98

       Vazao30    Vazao31
386  147318.08  146906.56
387  167932.16        NaN
388  184082.62  183607.58

[3 rows x 31 columns]
Vazao22
Vazao28
['LW_to_R', 'R_to_HW', 'HW_to_F', 'F_to_LW', 'LW_to_R', 'R_to_HW', 'HW_to_F', 'F_to_LW', 'LW_to_R', 'R_to_HW', 'HW_to_F']

6
       Vazao01    Vazao02     Vazao03     Vazao04     Vazao05     Vazao06  \
381   96329.31   96504.92   96329.310   97384.734   98444.450   99153.330
382   95453.10   93883.49   93015.710   92669.445   91461.336   90945.390
383  109828.71  109092.07  108173.890  107258.620  106528.500  105800.260
384  122057.28  121099.50  120526.195  119382.640  118622.550  117296.766
385  147112.27  146700.98  146700.980  146495.500  145264.880  144446.620
386  166781.16  166321.48  166091.810  165862.250  165403.440  164716.000

       Vazao07     Vazao08     Vazao09    Vazao10  ...     Vazao22    Vazao23  \
381  100398.43  101470.290  102546.414  104892.59  ...  120526.195  121865.50
382   90430.55   90259.180   90602.040   91117.25  ...   93883.490   94579.89
383  104892.59  104892.590  104530.350  104530.35  ...  100042.090   99153.33
384  116541.69  115788.445  115224.710  114849.46  ...  109460.160  108908.20
385  143630.12  142611.920  140988.450  139977.34  ...  128840.570  127083.17
386  163572.40  163115.720  162431.470  161293.20  ...  153124.280  152289.67

       Vazao24     Vazao25    Vazao26     Vazao27     Vazao28     Vazao29  \
381  123788.41  125141.140  126110.76  127472.920  128253.766  129232.336
382   94754.29   95278.220   95803.23   96856.484   97032.445   96680.640
383   98798.65   98798.650   99153.33   98798.650   98798.650   98444.450
384  108908.20  108724.450  108908.20  109276.055  109828.710  110382.414
385  125528.65  124174.336  123595.60  123210.340  122825.540  122441.190
386  150625.61  149589.050  149175.17  148968.390  148348.720  147936.140

        Vazao30    Vazao31
381  129820.810  130213.69
382   96504.920        NaN
383   97914.055   97208.53
384  110382.414        NaN
385  122249.180  122057.28
386  147318.080  146906.56

[6 rows x 31 columns]
Vazao28
Vazao24
['LW_to_R', 'R_to_HW', 'HW_to_F', 'F_to_LW', 'LW_to_R', 'R_to_HW', 'HW_to_F', 'F_to_LW', 'LW_to_R', 'R_to_HW', 'HW_to_F', 'F_to_LW']

3
       Vazao01    Vazao02    Vazao03     Vazao04    Vazao05    Vazao06  \
381   96329.31   96504.92   96329.31   97384.734   98444.45   99153.33
379  159024.69  158798.42  158798.42  159251.050  160384.52  161520.64
380  130607.01  131000.77  131394.98  132382.450  133769.55  134365.69

       Vazao07    Vazao08     Vazao09    Vazao10  ...     Vazao22    Vazao23  \
381  100398.43  101470.29  102546.414  104892.59  ...  120526.195  121865.50
379  161748.19  162659.45  164029.530  165862.25  ...  174426.330  175360.75
380  135361.44  137160.75  138566.360  139170.40  ...  149796.140  151248.83

       Vazao24    Vazao25    Vazao26    Vazao27     Vazao28     Vazao29  \
381  123788.41  125141.14  126110.76  127472.92  128253.766  129232.336
379  176296.84  177469.28  179115.06  179586.20  180293.700         NaN
380  152706.77  154588.95  155417.40  156091.67  156766.900  157217.600

       Vazao30    Vazao31
381  129820.81  130213.69
379        NaN        NaN
380  157668.72  158346.22

[3 rows x 31 columns]
Vazao24
Vazao14
['LW_to_R', 'R_to_HW', 'HW_to_F', 'F_to_LW', 'LW_to_R', 'R_to_HW', 'HW_to_F', 'F_to_LW', 'LW_to_R', 'R_to_HW', 'HW_to_F', 'F_to_LW', 'LW_to_R']

7
       Vazao01    Vazao02    Vazao03    Vazao04    Vazao05    Vazao06  \
373  201454.22  200231.06  199742.50  198522.81  197548.88  197305.64
374  217327.98  216574.98  215822.83  215321.89  215321.89  214821.34
375  224651.86  223636.86  223636.86  223636.86  223636.86  223383.36
376  222370.28  222370.28  222370.28  222370.28  222623.40  222623.40
377  205631.47  205878.08  206371.60  207359.81  208349.60  208845.08
378  181948.12  182658.70  183132.94  184320.31  185033.97  185510.23
379  159024.69  158798.42  158798.42  159251.05  160384.52  161520.64

       Vazao07    Vazao08    Vazao09    Vazao10  ...    Vazao22    Vazao23  \
373  195848.31  195121.00  194152.67  192944.50  ...  182184.88  181002.12
374  214321.17  214321.17  213571.66  212823.02  ...  207359.81  207359.81
375  223383.36  223636.86  223383.36  223129.94  ...  218836.62  219340.28
376  223129.94  223383.36  224144.17  224651.86  ...  224905.84  225159.92
377  209340.95  210830.90  212573.66  213571.66  ...  217327.98  217830.48
378  186941.52  187658.53  189095.30  190295.39  ...  198035.64  199498.36
379  161748.19  162659.45  164029.53  165862.25  ...  174426.33  175360.75

       Vazao24    Vazao25    Vazao26    Vazao27    Vazao28    Vazao29  \
373  180057.77  178644.31  177469.28  175127.00  173959.73  172795.10
374  206618.50  206371.60  205878.08  205138.55  204892.23  204399.90
375  219340.28  219844.31  219340.28  218584.95  218333.36  218584.95
376  224905.84  224905.84  224905.84  224905.84  224397.97  224397.97
377  218584.95  219340.28  220601.10  220348.73  221358.73  221864.31
378  200231.06  200964.66  201944.17  202679.86  203416.42  204399.90
379  176296.84  177469.28  179115.06  179586.20  180293.70        NaN

       Vazao30    Vazao31
373  171168.98  170242.08
374  203662.14  202434.53
375  217579.19        NaN
376  224397.97  224397.97
377  222370.28        NaN
378  204892.23  205138.55
379        NaN        NaN

[7 rows x 31 columns]
Vazao14
Vazao5
['LW_to_R', 'R_to_HW', 'HW_to_F', 'F_to_LW', 'LW_to_R', 'R_to_HW', 'HW_to_F', 'F_to_LW', 'LW_to_R', 'R_to_HW', 'HW_to_F', 'F_to_LW', 'LW_to_R', 'R_to_HW']

2
       Vazao01    Vazao02    Vazao03    Vazao04    Vazao05    Vazao06  \
372  168854.86  167471.44  166091.81  164716.00  163572.40  162431.47
373  201454.22  200231.06  199742.50  198522.81  197548.88  197305.64

       Vazao07    Vazao08    Vazao09    Vazao10  ...    Vazao22    Vazao23  \
372  161520.64  159704.11  158120.28  156992.19  ...  143018.88  140381.45
373  195848.31  195121.00  194152.67  192944.50  ...  182184.88  181002.12

       Vazao24    Vazao25    Vazao26    Vazao27    Vazao28    Vazao29  \
372  139371.97  138365.23  137561.80  134763.66  134166.86  132976.25

In [7]:
import numpy as np
import math

# lista_periodo = []
# lista_media_vazao = []

x = df.loc[df['year'] >= 2024 ].copy()
x = x.loc[x['year'] <= 2024].copy()
x = x.loc[x['month'] >= 5 ].copy()
x = x.loc[x['month'] <= 12].copy()
x = x.drop(columns=['Data','year','month','day','Maxima','Media','Minima'])
print( len(x))
# print(x)
print(str('Vazao')+str(df_period_limits['day'][99]))

lista_periodo.append(df_period_limits['type'][99])

lista_dias = []
x_1 = x[0:1].copy()
# print(x_1)
for j in range(int(df_period_limits['day'][99]),31):
      # print(j)
  if j < 10:
    media1 = x_1[str('Vazao0')+str(j)].mean()
    lista_dias.append(media1)

  else:
    media1 = x_1[str('Vazao')+str(j)].mean()
    lista_dias.append(media1)

x_2 = x[-1:].copy()
# print(x_2)
for k in range(int(df_period_limits['day'][i+1]),31):
      # print(k)
  if k < 10:
    media2 = x_2[str('Vazao0')+str(k)]
    lista_dias.append(media2.mean())
      # print(media2)
  else:
    media2 = x_2[str('Vazao')+str(k)]
    lista_dias.append(media2.mean())
print(lista_dias)
cleaned = [x for x in lista_dias if not (isinstance(x, float) and math.isnan(x))]
cleaned_mean = sum(cleaned)/len(lista_dias)

media = x[1:-1].mean(axis=1).mean()
cleaned_mean = (media + cleaned_mean)/2

lista_media_vazao.append(cleaned_mean)


print(lista_media_vazao)
print(lista_periodo)

8
Vazao29
[np.float64(96504.92), np.float64(98267.54), np.float64(206124.8)]
[np.float64(132135.74928571426), np.float64(178324.6838930596), np.float64(165665.86725531917), np.float64(109090.80271397848), np.float64(159619.0427026468), np.float64(200161.23493580017), np.float64(168770.3892857143), np.float64(109919.31528837641), np.float64(141689.67809715823), np.float64(187973.93025641018), np.float64(167971.94508333335), np.float64(127037.20871223118), np.float64(156509.26001190476), np.float64(189790.54376224056), np.float64(162023.60844444443), np.float64(116578.9407626728), np.float64(142678.18405555555), np.float64(206425.27627007983), np.float64(183063.79280555557), np.float64(114383.06567380953), np.float64(147186.2496784562), np.float64(187641.79376545697), np.float64(178445.254), np.float64(104159.9485097542), np.float64(154496.4856773399), np.float64(192157.3945125448), np.float64(166063.56238095235), np.float64(116646.54309039589), np.float64(152792.56766071427), np.float64(201770.26519892475), np.float64(196750.02625), np.float64(114920.31461430108), np.float64(151046.11952346042), np.float64(195144.49283179722), np.float64(177254.5376923077), np.float64(123682.43860833332), np.float64(147122.04166666666), np.float64(203274.96407891536), np.float64(185912.33687499998), np.float64(125298.33978780746), np.float64(149214.789), np.float64(183025.31028530464), np.float64(169613.685), np.float64(136244.9202111729), np.float64(149854.9129534884), np.float64(190720.28625301324), np.float64(162837.60815999997), np.float64(103080.74733037633), np.float64(148226.72101190477), np.float64(180563.7349375079), np.float64(175660.20759999997), np.float64(116004.58807750206), np.float64(150666.27463608026), np.float64(193666.54681003583), np.float64(168239.77187499995), np.float64(126322.32968953854), np.float64(154595.29489080462), np.float64(195550.16219969274), np.float64(171769.7223147605), np.float64(124781.3575430352), np.float64(138929.42266666668), np.float64(180999.04104059143), np.float64(171839.26405405405), np.float64(106080.17694964157), np.float64(160096.87898069495), np.float64(201415.74048783246), np.float64(183308.0648275862), np.float64(136644.78661182796), np.float64(154536.10685476192), np.float64(184493.99160463712), np.float64(164391.1825192308), np.float64(110485.55867642681), np.float64(129790.93746153844), np.float64(186521.60465002473), np.float64(164827.16869387752), np.float64(119278.7440951613), np.float64(142250.53756666664), np.float64(219826.38221447775), np.float64(202542.5635714286), np.float64(128126.49152834601), np.float64(159893.37073045823), np.float64(205831.04747849464), np.float64(182633.59722222225), np.float64(114141.14297255377), np.float64(136688.0720909091), np.float64(185957.1281573925), np.float64(190126.71041666667), np.float64(143118.0334922939), np.float64(141304.2671), np.float64(193509.33898146707), np.float64(170410.18369565214), np.float64(110683.14230716479), np.float64(146860.17380952384), np.float64(203547.3328612903), np.float64(171605.00722222222), np.float64(142375.47641754642), np.float64(162794.57918701298), np.float64(205181.13442284643), np.float64(181229.005483871), np.float64(148533.56804979796), np.float64(198010.68972222222), np.float64(180306.45410256414), np.float64(119580.2090948276), np.float64(193923.1057701613), np.float64(174051.1739153226), np.float64(122697.83812982638), np.float64(201998.4205119392), np.float64(184040.40156250005), np.float64(136730.59430094727), np.float64(190479.61224086024), np.float64(171801.6035483871), np.float64(137301.26443548387), np.float64(203283.95672727854), np.float64(179846.42681818182), np.float64(149345.82601815456), np.float64(198614.23958110274), np.float64(166808.01380000002), np.float64(111817.2366218638), np.float64(214749.52171511773), np.float64(197150.93499999997), np.float64(179420.35228571427), np.float64(228570.40154197457), np.float64(190831.03727272723), np.float64(127765.86735551074), np.float64(189753.36151084624), np.float64(180788.90305555554), np.float64(118005.62014813063), np.float64(169781.06838709678), np.float64(203966.25307692305), np.float64(129132.97864749105)]
['LW_to_R', 'R_to_HW', 'HW_to_F', 'F_to_LW', 'LW_to_R', 'R_to_HW', 'HW_to_F', 'F_to_LW', 'LW_to_R', 'R_to_HW', 'HW_to_F', 'F_to_LW', 'LW_to_R', 'R_to_HW', 'HW_to_F', 'F_to_LW', 'LW_to_R', 'R_to_HW', 'HW_to_F', 'F_to_LW', 'LW_to_R', 'R_to_HW', 'HW_to_F', 'F_to_LW', 'LW_to_R', 'R_to_HW', 'HW_to_F', 'F_to_LW', 'LW_to_R', 'R_to_HW', 'HW_to_F', 'F_to_LW', 'LW_to_R', 'R_to_HW', 'HW_to_F', 'F_to_LW', 'LW_to_R', 'R_to_HW', 'HW_to_F', 'F_to_LW', 'LW_to_R', 'R_to_HW', 'HW_to_F', 'F_to_LW', 'LW_to_R', 'R_to_HW', 'HW_to_F', 'F_to_LW', 'LW_to_R', 'R_to_HW', 'HW_to_F', 'F_to_LW', 'LW_to_R', 'R_to_HW', 'HW_to_F', 'F_to_LW', 'LW_to_R', 'R_to_HW', 'HW_to_F', 'F_to_LW', 'LW_to_R', 'R_to_HW', 'HW_to_F', 'F_to_LW', 'LW_to_R', 'R_to_HW', 'HW_to_F', 'F_to_LW', 'LW_to_R', 'R_to_HW', 'HW_to_F', 'F_to_LW', 'LW_to_R', 'R_to_HW', 'HW_to_F', 'F_to_LW', 'LW_to_R', 'R_to_HW', 'HW_to_F', 'F_to_LW', 'LW_to_R', 'R_to_HW', 'HW_to_F', 'F_to_LW', 'LW_to_R', 'R_to_HW', 'HW_to_F', 'F_to_LW', 'LW_to_R', 'R_to_HW', 'HW_to_F', 'F_to_LW', 'LW_to_R', 'R_to_HW', 'HW_to_F', 'F_to_LW', 'LW_to_R', 'R_to_HW', 'HW_to_F', 'LW_to_R', 'R_to_HW', 'HW_to_F', 'LW_to_R', 'R_to_HW', 'HW_to_F', 'LW_to_R', 'R_to_HW', 'HW_to_F', 'LW_to_R', 'R_to_HW', 'HW_to_F', 'LW_to_R', 'R_to_HW', 'HW_to_F', 'LW_to_R', 'R_to_HW', 'HW_to_F', 'LW_to_R', 'R_to_HW', 'HW_to_F', 'LW_to_R', 'R_to_HW', 'HW_to_F', 'LW_to_R', 'R_to_HW', 'HW_to_F', 'LW_to_R', 'R_to_HW', 'HW_to_F', 'LW_to_R']

In [8]:
df_media_vazao = pd.DataFrame(list(zip(lista_periodo, lista_media_vazao)),
               columns =['water_period', 'media_vazao'])

df_media_vazao=df_media_vazao.replace('LW_to_R', 'R')
df_media_vazao=df_media_vazao.replace('R_to_HW', 'HW')
df_media_vazao=df_media_vazao.replace('HW_to_F', 'F')
df_media_vazao=df_media_vazao.replace('F_to_LW', 'LW')
df_media_vazao=df_media_vazao.replace('F_to_L', 'LW')
df_media_vazao

    water_period    media_vazao
0              R  132135.749286
1             HW  178324.683893
2              F  165665.867255
3             LW  109090.802714
4              R  159619.042703
..           ...            ...
125            F  180788.903056
126            R  118005.620148
127           HW  169781.068387
128            F  203966.253077
129            R  129132.978647

[130 rows x 2 columns]

In [9]:
df_media_vazao = pd.concat([df_media_vazao,df_period_limits],axis=1)
df_media_vazao

,water_period,media_vazao,Data,type,day,month,year,longitude,latitude,time_start
0,R,132135.749286,1990-01-18 01:12:00.000000000,LW_to_R,18,1,1990,-55.5131,-1.9192,1990-01-18
1,HW,178324.683893,1990-02-23 01:06:12.413793152,R_to_HW,23,2,1990,-55.5131,-1.9192,1990-02-23
2,F,165665.867255,1990-08-06 23:15:16.770186368,HW_to_F,6,8,1990,-55.5131,-1.9192,1990-08-06
3,LW,109090.802714,1990-09-09 06:25:30.708661376,F_to_LW,9,9,1990,-55.5131,-1.9192,1990-09-09
4,R,159619.042703,1990-12-22 21:55:51.724137856,LW_to_R,22,12,1990,-55.5131,-1.9192,1990-12-22
...,...,...,...,...,...,...,...,...,...,...
125,F,180788.903056,2023-08-01 20:06:29.189189120,HW_to_F,1,8,2023,-55.5131,-1.9192,2023-08-01
126,R,118005.620148,2023-08-25 18:37:31.737451520,LW_to_R,25,8,2023,-55.5131,-1.9192,2023-08-25
127,HW,169781.068387,2024-03-25 23:32:02.330097152,R_to_HW,25,3,2024,-55.5131,-1.9192,2024-03-25
128,F,203966.253077,2024-04-06 10:42:51.428571648,HW_to_F,6,4,2024,-55.5131,-1.9192,2024-04-06
129,R,129132.978647,2024-05-30 21:51:25.714285824,F_to_L,30,5,2024,-55.5131,-1.9192,2024-05-30

In [10]:
df_media_vazao.describe()

,media_vazao,Data,day,month,year,longitude,latitude
count,130.000000,130,130.000000,130.000000,130.000000,1.300000e+02,1.300000e+02
mean,162504.442235,2006-06-02 04:45:25.656111488,16.046154,6.338462,2005.930769,-5.551310e+01,-1.919200e+00
min,103080.747330,1990-01-18 01:12:00,1.000000,1.000000,1990.000000,-5.551310e+01,-1.919200e+00
25%,137708.303993,1998-02-23 22:16:40.805114880,8.000000,2.000000,1998.000000,-5.551310e+01,-1.919200e+00
50%,166435.788090,2006-01-13 06:08:16.922033920,17.000000,8.000000,2005.500000,-5.551310e+01,-1.919200e+00
75%,187361.746487,2014-01-18 10:38:47.272727296,24.000000,9.000000,2013.750000,-5.551310e+01,-1.919200e+00
max,228570.401542,2024-05-30 21:51:25.714285824,31.000000,12.000000,2024.000000,-5.551310e+01,-1.919200e+00
std,30583.028376,NaN,9.216485,3.594901,9.899643,7.132915e-14,3.789361e-15

In [11]:
# aggregated_data.to_csv('C:/Users/l_v_v/Documents/GitHub/py6s_harmonize_sample/datasets/Parameters Time series/mean_watershed_discharge_cota.csv')
df_media_vazao.to_csv('/content/drive/MyDrive/CURUAI_PROCESS//mean_watershed_discharge_cota.csv')